apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: zearnaldo1980/argocd-fullcycle
  newTag: 4c77d3cfe0d1d2c68088aa6f78685809e2c0550b
